version: '3.3'
services:
    mongo:
        ports:
            - '27019:27017'
        container_name: runailocal-db
        restart: always
        # logging:
        #     options:
        #         max-size: 1g
        image: mongo:latest

    minio:
        image: minio/minio
        container_name: minio
        restart: always
        ports:
            - '9000:9000'  # MinIO API
            - '9001:9001'  # MinIO Console (Web UI)
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data

volumes:
    minio_data: