version: '3.8'
services:
    rail-be:
        container_name: rail-be
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - mongo
            - minio
        networks:
            - rail-network
        
    mongo:
        ports:
            - '27019:27017'
        container_name: runailocal-db
        restart: always
        # logging:
        #     options:
        #         max-size: 1g
        image: mongo:latest
        networks:
            - rail-network
        volumes:
            - mongo_data:/data/db

    minio:
        image: minio/minio
        container_name: minio
        restart: always
        ports:
            - '9000:9000'  # MinIO API
            - '9001:9001'  # MinIO Console (Web UI)
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
        networks:
            - rail-network

networks:
    rail-network:
        driver: bridge

volumes:
    minio_data:
    mongo_data: