version: '3.8'
services:
    rail-be:
        container_name: rail-be
        build:
            context: .
            dockerfile: Dockerfile
        # network_mode: "host"
        ports:
            - '8000:8000'
        networks:
            - rail-network
        # No ports needed with host network
        volumes:
            - .:/app
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - mongo
            - minio
        
    mongo:
        container_name: runailocal-db
        restart: always
        # logging:
        #     options:
        #         max-size: 1g
        image: mongo:latest
        # network_mode: "host"
        ports:
            - '27017:27017'
        # No ports needed with host network
        networks:
            - rail-network
        environment:
            # Set MongoDB to listen on specific port
            MONGO_PORT: 27017
        command: mongod --port 27017 --bind_ip 0.0.0.0
        volumes:
            - mongo_data:/data/db

    minio:
        image: minio/minio
        container_name: minio-2
        restart: always
        # network_mode: "host"
        ports:
            - '9000:9000' # for storage client
            - '9001:9001' # for webui
        # No ports needed with host network
        networks:
            - rail-network
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001" --address ":9000"
        volumes:
            - minio_data:/data

# No networks section needed with host networking

volumes:
    minio_data:
    mongo_data:

networks:
  rail-network:
    driver: bridge